name = "buddy-presence"
main = "src/index.js"
compatibility_date = "2024-12-01"

[[kv_namespaces]]
binding = "KV"
id = "9bd5a46e2d184b6da59c56e85297f74f"

[durable_objects]
bindings = [
  { name = "USER_CHANNEL", class_name = "UserChannel" }
]

[[migrations]]
tag = "v1"
new_classes = ["UserChannel"]
